model_ref: diabetes-binary-classification-v1

optimizer:
  type: torch.optim.Adam
  lr: 0.001

config:
  epochs: 100
  batch_size: 32
  learning_rate: 0.001
  validation_split: 0.2
  early_stopping_patience: 10
  checkpoint_every: 10
  save_best_only: true
  device: auto
  log_every: 10
  verbose: true