optimizer:
  type: torch.optim.Adam
loss:
  type: torch.nn.BCELoss
  inputs:
    pred: model.prediction
    target: outcome
config:
  epochs: 5
  batch_size: 32
  learning_rate: 0.01
  target_output_key: prediction
  reshape_targets: true
  validation_split: 0.2
  shuffle: true
  checkpoint_every: 5
  save_best_only: true
  device: auto
  log_every: 10
  verbose: true